// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: TestGrpc.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

public static partial class GrpcTestService
{
  static readonly string __ServiceName = "GrpcTestService";

  static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
  {
    #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
    if (message is global::Google.Protobuf.IBufferMessage)
    {
      context.SetPayloadLength(message.CalculateSize());
      global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
      context.Complete();
      return;
    }
    #endif
    context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
  }

  static class __Helper_MessageCache<T>
  {
    public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
  }

  static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
  {
    #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
    if (__Helper_MessageCache<T>.IsBufferMessage)
    {
      return parser.ParseFrom(context.PayloadAsReadOnlySequence());
    }
    #endif
    return parser.ParseFrom(context.PayloadAsNewBuffer());
  }

  static readonly grpc::Marshaller<global::EmployeeNameRequest> __Marshaller_EmployeeNameRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::EmployeeNameRequest.Parser));
  static readonly grpc::Marshaller<global::EmployeeName> __Marshaller_EmployeeName = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::EmployeeName.Parser));

  static readonly grpc::Method<global::EmployeeNameRequest, global::EmployeeName> __Method_GetEmployeeName = new grpc::Method<global::EmployeeNameRequest, global::EmployeeName>(
      grpc::MethodType.Unary,
      __ServiceName,
      "GetEmployeeName",
      __Marshaller_EmployeeNameRequest,
      __Marshaller_EmployeeName);

  /// <summary>Service descriptor</summary>
  public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
  {
    get { return global::TestGrpcReflection.Descriptor.Services[0]; }
  }

  /// <summary>Base class for server-side implementations of GrpcTestService</summary>
  [grpc::BindServiceMethod(typeof(GrpcTestService), "BindService")]
  public abstract partial class GrpcTestServiceBase
  {
    public virtual global::System.Threading.Tasks.Task<global::EmployeeName> GetEmployeeName(global::EmployeeNameRequest request, grpc::ServerCallContext context)
    {
      throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
    }

  }

  /// <summary>Client for GrpcTestService</summary>
  public partial class GrpcTestServiceClient : grpc::ClientBase<GrpcTestServiceClient>
  {
    /// <summary>Creates a new client for GrpcTestService</summary>
    /// <param name="channel">The channel to use to make remote calls.</param>
    public GrpcTestServiceClient(grpc::ChannelBase channel) : base(channel)
    {
    }
    /// <summary>Creates a new client for GrpcTestService that uses a custom <c>CallInvoker</c>.</summary>
    /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
    public GrpcTestServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
    {
    }
    /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
    protected GrpcTestServiceClient() : base()
    {
    }
    /// <summary>Protected constructor to allow creation of configured clients.</summary>
    /// <param name="configuration">The client configuration.</param>
    protected GrpcTestServiceClient(ClientBaseConfiguration configuration) : base(configuration)
    {
    }

    public virtual global::EmployeeName GetEmployeeName(global::EmployeeNameRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
    {
      return GetEmployeeName(request, new grpc::CallOptions(headers, deadline, cancellationToken));
    }
    public virtual global::EmployeeName GetEmployeeName(global::EmployeeNameRequest request, grpc::CallOptions options)
    {
      return CallInvoker.BlockingUnaryCall(__Method_GetEmployeeName, null, options, request);
    }
    public virtual grpc::AsyncUnaryCall<global::EmployeeName> GetEmployeeNameAsync(global::EmployeeNameRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
    {
      return GetEmployeeNameAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
    }
    public virtual grpc::AsyncUnaryCall<global::EmployeeName> GetEmployeeNameAsync(global::EmployeeNameRequest request, grpc::CallOptions options)
    {
      return CallInvoker.AsyncUnaryCall(__Method_GetEmployeeName, null, options, request);
    }
    /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
    protected override GrpcTestServiceClient NewInstance(ClientBaseConfiguration configuration)
    {
      return new GrpcTestServiceClient(configuration);
    }
  }

  /// <summary>Creates service definition that can be registered with a server</summary>
  /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
  public static grpc::ServerServiceDefinition BindService(GrpcTestServiceBase serviceImpl)
  {
    return grpc::ServerServiceDefinition.CreateBuilder()
        .AddMethod(__Method_GetEmployeeName, serviceImpl.GetEmployeeName).Build();
  }

  /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
  /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
  /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
  /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
  public static void BindService(grpc::ServiceBinderBase serviceBinder, GrpcTestServiceBase serviceImpl)
  {
    serviceBinder.AddMethod(__Method_GetEmployeeName, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::EmployeeNameRequest, global::EmployeeName>(serviceImpl.GetEmployeeName));
  }

}
#endregion
